In [53]:
import pandas as pd
import os

In [54]:
url = "https://raw.githubusercontent.com/ClaudiaSobral/treinamento-dados-end-to-end/refs/heads/main/src/imdb_movies.csv"
df = pd.read_csv(url)

In [55]:
df.head()

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
0,Creed III,03/02/2023,73.0,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,Released,English,75000000.0,2.716167e+08,AU
1,Avatar: The Way of Water,12/15/2022,78.0,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU
2,The Super Mario Bros. Movie,04/05/2023,76.0,"Animation, Adventure, Family, Fantasy, Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",The Super Mario Bros. Movie,Released,English,100000000.0,7.244590e+08,AU
3,Mummies,01/05/2023,70.0,"Animation, Comedy, Family, Adventure, Fantasy","Through a series of unfortunate events, three ...","Óscar Barberán, Thut (voice), Ana Esther Albor...",Momias,Released,"Spanish, Castilian",12300000.0,3.420000e+07,AU
4,Supercell,03/17/2023,61.0,Action,Good-hearted teenager William always lived in ...,"Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...",Supercell,Released,English,77000000.0,3.409420e+08,US

In [56]:
linhas = df.shape[0]

print(f"O dataset contém {linhas} registros.")

O dataset contém 10178 registros.

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10178 entries, 0 to 10177
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   names       10178 non-null  object
 1   date_x      10178 non-null  object
 2   score       10178 non-null  float64
 3   genre       10093 non-null  object
 4   overview    10178 non-null  object
 5   crew        10122 non-null  object
 6   orig_title  10178 non-null  object
 7   status      10178 non-null  object
 8   orig_lang   10178 non-null  object
 9   budget_x    10178 non-null  float64
 10  revenue     10178 non-null  float64
 11  country     10178 non-null  object
dtypes: float64(3), object(9)
memory usage: 954.3+ KB

In [58]:
df.isnull().sum()

names          0
date_x         0
score          0
genre         85
overview       0
crew          56
orig_title     0
status         0
orig_lang      0
budget_x       0
revenue        0
country        0
dtype: int64

In [59]:
df.duplicated().sum()

np.int64(0)

## Tratamento do dataset

## Investigação do dataset

In [60]:
data_max =  df.date_x.max()
data_min =  df.date_x.min()

print(f"A data mínima contida no datast é {data_min} e a data máxima é {data_max}")

A data mínima contida no datast é 01/01/1952  e a data máxima é 12/31/2023

In [61]:
df[df['orig_title'].str.contains('.Trap.')]

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
1648,Puss in Book: Trapped in an Epic Tale,06/20/2017,66.0,"Family, Fantasy, Animation, Comedy, Adventure","After tumbling into a magic storybook, Puss in...","Eric Bauza, Puss In Boots / Eames / Princess M...",Puss in Book: Trapped in an Epic Tale,Released,English,111000000.0,347509904.0,US
4979,JLA Adventures: Trapped in Time,01/21/2014,67.0,"Family, Animation, Action, Science Fiction",Get ready for a battle of the ages when the Ju...,"Diedrich Bader, Batman / Bruce Wayne / Narrato...",JLA Adventures: Trapped in Time,Released,English,178000000.0,437664915.2,US

In [62]:
df[df['orig_title'].str.contains('Cinderela')]

Empty DataFrame
Columns: [names, date_x, score, genre, overview, crew, orig_title, status, orig_lang, budget_x, revenue, country]
Index: []

In [70]:
start_date = 12/31/1986
end_date = 1/1/1988
mask = (df['date_x'] > start_date) & (df['date_x'] < end_date)

df.loc[mask]

TypeError: '>' not supported between instances of 'str' and 'float'

In [ ]:
df[df['orig_title'].str.contains('Cidade')]

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
2113,City of God,08/30/2002,84.0,"Drama, Crime","In the slums of Rio, two kids' paths diverge a...","Alexandre Rodrigues, Buscapé, Leandro Firmino,...",Cidade de Deus,Released,Portuguese,3300000.0,30641770.0,AU

In [ ]:
df[df['names'].str.contains('Eraser')]

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
5120,Eraser,09/19/1996,60.0,"Action, Drama, Mystery, Thriller",U.S. Marshall John Kruger erases the identitie...,"Arnold Schwarzenegger, U.S. Marshal John 'The ...",Eraser,Released,English,100000000.0,234400000.0,AU
7740,Eraserhead,01/01/1980,74.0,"Fantasy, Horror",First time father Henry Spencer tries to survi...,"Jack Nance, Henry Spencer, Charlotte Stewart, ...",Eraserhead,Released,English,100000.0,7097971.0,AU
9217,Eraser: Reborn,06/07/2022,66.0,"Action, Crime, Thriller",U.S. Marshal Mason Pollard specializes in “era...,"Dominic Sherwood, U.S. Marshal Mason Pollard, ...",Eraser: Reborn,Released,English,101000000.0,321357348.6,US

In [ ]:
df[df['names'].str.contains('Room')]

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
423,Wire Room,09/02/2022,66.0,"Action, Crime, Thriller",New recruit Justin Rosa must monitor arms-smug...,"Kevin Dillon, Justin Rosa, Bruce Willis, Shane...",Wire Room,Released,English,101000000.0,321357348.6,US
1034,War Room,08/28/2015,78.0,"Drama, Romance",The family-friendly movie explores the transfo...,"Karen Abercrombie, Clara Williams, Priscilla C...",War Room,Released,English,3000000.0,73989734.0,US
1238,The Immaculate Room,11/01/2022,56.0,"Mystery, Thriller, Drama, Science Fiction","Mike and Kate, a young couple, get the once-in...","Kate Bosworth, Kate, Emile Hirsch, Michael, As...",The Immaculate Room,Released,English,109200000.0,260090578.4,AU
1663,Escape Room: Tournament of Champions,07/01/2021,67.0,"Horror, Thriller, Mystery",Six people unwittingly find themselves locked ...,"Taylor Russell, Zoey Davis, Logan Miller, Ben ...",Escape Room: Tournament of Champions,Released,English,15000000.0,53493064.0,AU
2053,Delicious Room Salon Service 2,09/30/2019,52.0,Romance,We don't have an overview translated in Englis...,"이미선, , Min Jung, , Kim Soo-ji,",룸싸롱 : 맛있는 서비스2,Released,Korean,136400000.0,328929749.2,KR
2464,Escape Room,02/07/2019,65.0,"Horror, Thriller, Mystery",Six strangers find themselves in circumstances...,"Taylor Russell, Zoey Davis, Logan Miller, Ben ...",Escape Room,Released,English,9000000.0,155615727.0,AU
2743,Delicious Room Salon Service,08/09/2018,68.0,Romance,A room salon isn't doing well. There's only Mi...,"Kim Hee-jeong, Joo-hee, Yoon Da-hyun, Min-joo,...",룸싸롱 맛있는 서비스,Released,Korean,78200000.0,360564423.2,KR
3276,Room in Rome,05/07/2010,64.0,"Drama, Romance",A hotel room in the center of Rome serves as t...,"Elena Anaya, Alba, Natasha Yarovenko, Natasha,...",Habitación en Roma,Released,"Spanish, Castilian",36345000.0,844281.0,ES
3928,Room Salon College Girls,03/29/2018,0.0,Romance,Sexy female college students get part-time job...,"Kim Hee-jeong, , Yoon Da-hyun, , Choi Chul-min,",룸싸롱 여대생들,Released,Korean,181600000.0,175269998.8,KR
4079,The Room,11/06/2019,64.0,"Horror, Drama, Mystery, Science Fiction",Kate and Matt discover that a part of their ho...,"Olga Kurylenko, Kate, Kevin Janssens, Matt, Fr...",The Room,Released,English,39412225.8,44291.0,BE
4239,There Is a Japanese Woman in My Room,02/12/2019,47.0,"Drama, Romance",A determined Japanese woman gets a job in Kore...,"Mao Hamasaki, Sakura / Kento, Shin Yeon-woo, M...",내방에 일본여자가 있다,Released,Korean,129200000.0,947468745.8,KR
4503,Escape Room,08/31/2017,49.0,"Horror, Thriller, Fantasy",Four friends who partake in a popular Los Ange...,"Skeet Ulrich, Brice, Sean Young, Ramona, Chris...",Escape Room,Released,English,9000000.0,155615727.0,RU
4732,Room,01/15/2016,80.0,"Drama, Thriller","Held captive for 7 years in an enclosed space,...","Brie Larson, Joy ""Ma"" Newsome, Jacob Tremblay,...",Room,Released,English,13000000.0,36316727.0,GB
4967,Panic Room,04/11/2002,67.0,"Crime, Drama, Thriller",Trapped in their New York brownstone's panic r...,"Jodie Foster, Meg Altman, Kristen Stewart, Sar...",Panic Room,Released,English,48000000.0,196308367.0,AU
5425,Room Salon College Girls 3,04/17/2020,50.0,"Romance, Action","Hee-jung, a college student, uses up a lot of ...","Kim Ji-ah, , Jin Yi, , Hae Il, , Min Do-yoon, ...",룸싸롱 여대생들 3,Released,Korean,140400000.0,597705817.6,KR
5436,Escape Room,09/14/2017,45.0,"Horror, Thriller",Six friends test their intelligence in a game ...,"Evan Williams, Tyler, Annabelle Stephenson, Na...",Escape Room,Released,English,9000000.0,155615727.0,RU
6461,Four Rooms,03/28/1996,58.0,"Crime, Comedy",It's Ted the Bellhop's first night on the job....,"Tim Roth, Ted the Bellhop, Jennifer Beals, Ang...",Four Rooms,Released,English,4000000.0,4301000.0,AU
8665,Green Room,05/12/2016,67.0,"Horror, Crime, Thriller",A punk rock band becomes trapped in a secluded...,"Anton Yelchin, Pat, Imogen Poots, Amber, Alia ...",Green Room,Released,English,5000000.0,3807503.0,AU
8908,The Roommate,02/04/2011,54.0,"Thriller, Drama, Horror","When Sara, a young design student from Iowa, a...","Leighton Meester, Rebecca Evans, Minka Kelly, ...",The Roommate,Released,English,16000000.0,52545707.0,US
9734,Marvin's Room,12/18/1996,67.0,Drama,A leukemia patient attempts to end a 20-year f...,"Meryl Streep, Lee Wakefield Lacker, Diane Keat...",Marvin's Room,Released,English,23000000.0,12803305.0,US
10084,Fermat's Room,10/07/2007,66.0,"Mystery, Thriller",Four mathematicians who do not know each other...,"Lluís Homar, Hilbert, Santi Millán, Pascal, Al...",La Habitación de Fermat,Released,"Spanish, Castilian",118154097.6,661906631.6,ES