In [312]:
import pandas as pd
import datetime as dt

In [313]:
url = "https://raw.githubusercontent.com/ClaudiaSobral/treinamento-dados-end-to-end/refs/heads/main/src/imdb_movies.csv"
df = pd.read_csv(url)

In [314]:
df.head()

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
0,Creed III,03/02/2023,73.0,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,Released,English,75000000.0,2.716167e+08,AU
1,Avatar: The Way of Water,12/15/2022,78.0,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU
2,The Super Mario Bros. Movie,04/05/2023,76.0,"Animation, Adventure, Family, Fantasy, Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",The Super Mario Bros. Movie,Released,English,100000000.0,7.244590e+08,AU
3,Mummies,01/05/2023,70.0,"Animation, Comedy, Family, Adventure, Fantasy","Through a series of unfortunate events, three ...","Óscar Barberán, Thut (voice), Ana Esther Albor...",Momias,Released,"Spanish, Castilian",12300000.0,3.420000e+07,AU
4,Supercell,03/17/2023,61.0,Action,Good-hearted teenager William always lived in ...,"Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...",Supercell,Released,English,77000000.0,3.409420e+08,US

In [315]:
linhas = df.shape[0]

print(f"O dataset contém {linhas} registros.")

O dataset contém 10178 registros.

In [316]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10178 entries, 0 to 10177
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   names       10178 non-null  str
 1   date_x      10178 non-null  str
 2   score       10178 non-null  float64
 3   genre       10093 non-null  str
 4   overview    10178 non-null  str
 5   crew        10122 non-null  str
 6   orig_title  10178 non-null  str
 7   status      10178 non-null  str
 8   orig_lang   10178 non-null  str
 9   budget_x    10178 non-null  float64
 10  revenue     10178 non-null  float64
 11  country     10178 non-null  str
dtypes: float64(3), str(9)
memory usage: 6.9 MB

In [317]:
df.isnull().sum()

names          0
date_x         0
score          0
genre         85
overview       0
crew          56
orig_title     0
status         0
orig_lang      0
budget_x       0
revenue        0
country        0
dtype: int64

In [318]:
df.duplicated().sum()

np.int64(0)

## Tratamento do dataset

### Tratamento da data

In [319]:
df['data_editada'] = df['date_x'].str.strip()
df['data'] = pd.to_datetime(df['data_editada'], format='%m/%d/%Y')
df['data']

0       2023-03-02
1       2022-12-15
2       2023-04-05
3       2023-01-05
4       2023-03-17
           ...
10173   2016-12-28
10174   1990-08-24
10175   1990-12-21
10176   1995-07-11
10177   2020-07-20
Name: data, Length: 10178, dtype: datetime64[us]

In [320]:
df['orig_lang'] = df['orig_lang'].str.strip()

### Tratamento do elenco

In [ ]:
df['elenco_lista'] = df['crew'].str.split(', ')
df['elenco_lista']

for lista in df['elenco_lista']:
    for item in lista[::2]:
        print(item)

# Até aqui deu pra pegar os itens

Michael B. Jordan
Tessa Thompson
Jonathan Majors
Wood Harris
Phylicia Rashād
Mila Davis-Kent
Florian Munteanu
José Benavidez Jr.
Selenis Leyva
Sam Worthington
Zoe Saldaña
Sigourney Weaver
Stephen Lang
Kate Winslet
Cliff Curtis
Joel David Moore
CCH Pounder
Edie Falco
Chris Pratt
Anya Taylor-Joy
Charlie Day
Jack Black
Keegan-Michael Key
Seth Rogen
Fred Armisen
Kevin Michael Richardson
Sebastian Maniscalco
Óscar Barberán
Ana Esther Alborg
Luis Pérez Reina
María Luisa Solá
Jaume Solà
José Luis Mediavilla
José Javier Serrano Rodríguez
Aleix Estadella
María Moscardó
Skeet Ulrich
Anne Heche
Daniel Diemer
Jordan Kristine Seamón
Alec Baldwin
Richard Gunn
Praya Lundberg
Johnny Wactor
Anjul Nigam
Keri Russell
Alden Ehrenreich
O'Shea Jackson Jr.
Ray Liotta
Kristofer Hivju
Margo Martindale
Christian Convery
Isiah Whitlock Jr.
Jesse Tyler Ferguson
Keanu Reeves
Donnie Yen
Bill Skarsgård
Ian McShane
Laurence Fishburne
Lance Reddick
Clancy Brown
Hiroyuki Sanada
Shamier Anderson
Antonio Banderas
Salma Hayek
Harvey Guillén
Wagner Moura
Florence Pugh
Olivia Colman
Ray Winstone
Samson Kayo
John Mulaney
Paul Bianchi
Erin Coker
Jack Pearson
Anthony Jensen
Neli Sabour
Karan Sagoo
Natalie Storrs
Justin Tanks
Jenny Tran
Chloe Guidry
Nhedrick Jabier
Carmina Garay
Billy Slaughter
Carli McIntyre
Laura Coover
Presley Richardson
Sean Papajohn
Legend Jay Jones
Craig David Dowsett
Chris Cordell
Amber Doig-Thorne
Natasha Tosini
Maria Taylor
Nikolai Leon
May Kelly
Danielle Ronald
Danielle Scott
María Evoli
Diana Bracho
Tina Romero
Norma Lazareno
Pilar Santacruz
Salvador Sánchez
Julio Bracho
Ramón Medína
Adam Sandler
Jennifer Aniston
Mark Strong
Mélanie Laurent
Jodie Turner-Smith
John Kani
Kuhoo Verma
Dany Boon
Adeel Akhtar
Letitia Wright
Lupita Nyong'o
Danai Gurira
Winston Duke
Dominique Thorne
Tenoch Huerta Mejía
Angela Bassett
Florence Kasumba
Michaela Coel
Russell Crowe
Daniel Zovatto
Alex Essoe
Franco Nero
Laurel Marsden
Cornell John
Ralph Ineson
River Hawkins
Pablo Raybould
Matt Hookings
Ray Winstone
Jodhi May
Marton Csokas
Russell Crowe
Steven Berkoff
Julian Glover
Dave Bautista
Jonathan Groff
Ben Aldridge
Kristen Cui
Nikki Amuka-Bird
Rupert Grint
Abby Quinn
Clare Louise Frost
McKenna Kerrigan
Alice Orr-Ewing
Joe Doyle
Eveline Hall
Peter Mensah
Joe Anderson
Brian Caspe
Spencer Wilding
James Faulkner
Victoria Chilap
Natalia Reddersen
Willy Semler
Alexandra Von Hummel
Felipe Valenzuela
Jon Øigarden
Ida Elise Broch
Sven Nordin
Eivind Sander
Axel Bøyum
Morten Svartveit
Anatole Taubman
Thorbjørn Harr
Gard B. Eidsvold
Noah Jupe
Mandy Patinkin
Brian Tyree Henry
Natasia Demetriou
Sian Clifford
Benedict Wong
Miranda Richardson
Kirby Howell-Baptiste
Aasif Mandvi
Gerard Butler
Mike Colter
Yoson An
Tony Goldwyn
Daniella Pineda
Paul Ben-Victor
Remi Adeleke
Joey Slotnick
Evan Dane Taylor
Jim Caviezel
Maia Morgenstern
Christo Jivkov
Francesco De Vito
Monica Bellucci
Mattia Sbragia
Toni Bertorelli
Luca Lionello
Hristo Shopov
David Giuntoli
Patrick Fabian
John DiMaggio
Karan Brar
Navid Negahban
Darin De Paul
Emily O'Brien
Christopher Gorham
David Dastmalchian
Zachary Levi
Asher Angel
Jack Dylan Grazer
Grace Caroline Currey
Helen Mirren
Lucy Liu
Rachel Zegler
Adam Brody
Meagan Good
Jena Malone
Danny Huston
Thoren Ferguson
Janet Suzman
Ian Pirie
Steffan Cennydd
Will Keen
Alexandra Lewis
Kit Rakusen
Maxi Witrak
Ego Mikitas
Michael Marcel
Tania Fox
Konstantin Podprugin
Lindsey Marie Wilson
Lydia Hunter
Reginald Stalling III
Terrance Livingston Jr.
Dwayne Johnson
Aldis Hodge
Noah Centineo
Sarah Shahi
Quintessa Swindell
Marwan Kenzari
Mo Amer
Bodhi Sabongui
Pierce Brosnan
Noelle Perdue
Mike Stabile
FSC
Self - Porn Performer
Self - Porn Performer
Self - Journalist
Bree Mills
Cherie DeVille
Asa Akira
Natassia Dreams
Allison Williams
Violet McGraw
Jenna Davis
Amie Donald
Jen Van Epps
Brian Jordan Alvarez
Ronny Chieng
Stephane Garneau-Monten
Amy Usherwood
Paul Rudd
Evangeline Lilly
Jonathan Majors
Kathryn Newton
Michelle Pfeiffer
Michael Douglas
Corey Stoll
Bill Murray
William Jackson Harper
Rallén Montenegro
Arón Piper
Enrique Arce
Roberto García Ruiz
Loreto Aravena
Alejandro Trejo
Eduardo Paxeco
Camilo Arancibia
Teresa Ramos
Kevin Hart
John Travolta
Nathalie Emmanuel
Jean Reno
Josh Hartnett
Kenneth Trujillo
Joshua Lamboy
Brandon Quinn
Milana Vayntrub
María Romanillos
Ruth Díaz
Urko Olazábal
Pablo Revuelta
José Sacristán
Daniela Bini
Cristina Castaño
Silma López
Daniel Arias
Portia Chellelynn
Julie Anne Prescott
Andrea Collins
Erin Trimble
Solon Tsangaras
John Johnson
Shonda Laverty
Bill Levin
Joe Padgett
Keanu Reeves
Common
Ian McShane
Laurence Fishburne
Riccardo Scamarcio
Ruby Rose
Lance Reddick
Peter Stormare
Bridget Moynahan
Gideon Adlon
Bethlehem Million
Dylan Sprayberry
Marc Menchaca
Jane Adams
Joel Courtney
Chris Reid
Duane Stephens
Logan Murphy
Tom Berenger
Cam Gigandet
Jeff Fahey
Jonathan Avigdori
Sara Seyed
Rafael Cabrera
Rodrigo Abed
Tonantzin Esparza
Jennifer Lopez
Josh Duhamel
Jennifer Coolidge
Sônia Braga
Lenny Kravitz
D'Arcy Carden
Cheech Marin
Selena Tan
Desmin Borges
Keanu Reeves
Halle Berry
Ian McShane
Laurence Fishburne
Mark Dacascos
Asia Kate Dillon
Lance Reddick
Anjelica Huston
Tobias Segal
Meg Donnelly
Harry Shum Jr.
Darren Criss
Jensen Ackles
Matt Bomer
Cynthia Hamidi
Yuri Lowenthal
Gideon Adlon
Ely Henry
Grace Caroline Currey
Virginia Gardner
Jeffrey Dean Morgan
Mason Gooding
Jasper Cole
Darrell Dennis
Julia Pace Mitchell
Treach
Quinton Jackson
Khalil Rountree Jr.
Anderson Silva
Richard Grieco
A.J. McKee
Gigi Gustin
Meredith Thomas
Ashley Doris
Frank Grillo
Eric Dane
Annabeth Gish
Mercedes Mason
Peter Greene
Beau Knapp
Thomas Dekker
Maurice Compte
Sufe Bradshaw
Brendan Fraser
Sadie Sink
Hong Chau
Ty Simpkins
Samantha Morton
Sathya Sridharan
Jacey Sink
Wilhelm Schalaudek
Jacqueline Byers
Colin Salmon
Christian Navarro
Lisa Palfrey
Nicholas Ralph
Ben Cross
Virginia Madsen
Tom Forbes
Velizar Binev
Josh Duhamel
Elisha Cuthbert
Mel Gibson
Nestor Carbonell
Lorenzo Yearby
Swen Temmel
Keith Arthur Bolden
Dylan Flashner
Olivia d'Abo
Alisha Weir
Emma Thompson
Lashana Lynch
Stephen Graham
Andrea Riseborough
Sindhu Vee
Charlie Hodson-Prior
Meesha Garbett
Rei Yamauchi Fulker
Nancy Cartwright
Yeardley Smith
Dan Castellaneta
Julie Kavner
Andrea Bocelli
Matteo Bocelli
Virginia Bocelli
Natsuki Hanae
Akari Kito
Hiro Shimono
Yoshitsugu Matsuoka
Satoshi Hino
Takahiro Sakurai
Katsuyuki Konishi
Saori Hayami
Kenichi Suzumura
Natalia Solián
Alfonso Dosal
Mayra Batalla
Mercedes Hernández
Aida López
Martha Claudia Moreno
Enoc Leaño
Pablo Guisa Koestinger
Sonia Couoh
Germán Palacios
Victoria Almeida
Gloria Carrá
César Bordón
Germán de Silva
Miguel Jordán
Héctor Calori
María Inés Banegas
Daniel Miglioranza
Kang Soo-youn
Kim Hyun-joo
Ryu Kyung-soo
Uhm Ji-won
Lee Dong-hee
Han Woo-yeol
Lee Ga-kyung
Shin Min-jae
Kim Sun-hyuk
Tom Hanks
Mariana Treviño
Rachel Keller
Manuel Garcia-Rulfo
Cameron Britton
Kailey Hyman
Mike Birbiglia
Elle Chapman
Joe Fishel
Woody Harrelson
Kaitlin Olson
Cheech Marin
Matt Cook
Ernie Hudson
Madison Tevlin
Joshua Felder
Kevin Iannucci
Ashton Gunning
Chris Pine
Michelle Rodriguez
Regé-Jean Page
Justice Smith
Sophia Lillis
Hugh Grant
Jason Wong
Chloe Coleman
Daisy Head
Ine Marie Wilmann
Kim S. Falck-Jørgensen
Mads Sjøgård Pettersen
Gard B. Eidsvold
Anneke von der Lippe
Dennis Storhøi
Karoline Viktoria Sletteng Garvang
Yusuf Toosh Ibra
Ameli Olving Sælevik
James Marsden
Ben Schwartz
Tika Sumpter
Natasha Rothwell
Adam Pally
Shemar Moore
Colleen O'Shaughnessey
Lee Majdoub
Idris Elba
Robert De Niro
Chazz Palminteri
Lillo Brancato
Francis Capra
Taral Hicks
Kathrine Narducci
Clem Caserta
Alfred Sauchelli Jr.
Frank Pietrangolare
Daniil Medvedev
Bernard Jacobsen
Stephen Thomas Ochsner
Liza Klimova
Kate Lann
Jonathan Salway
Jordan Worsley
David Andrew Grout
Andrey Kurganov
Lin-Manuel Miranda
Stephanie Beatriz
Adassa
Carolina Gaitán
Jessica Darrow
Diane Guerrero
Mauro Castillo
Angie Cepeda
Olga Merediz
Wai-Kin Lam
Serina Hayakawa
Kaera Uehara
Winnie Leung
Hikaru Wakana
Lee Kin-Yan
Tam Kon-Chung
Samuel Leung Cheuk-Moon
Frankie Ng
Tom Cruise
Miles Teller
Jennifer Connelly
Jon Hamm
Glen Powell
Ed Harris
Val Kilmer
Lewis Pullman
Charles Parnell
Dennis Quaid
Heather Graham
Jesse Metcalfe
Abbey Rhyne
Jessi Case
Brett Rice
Rocky Myers
Selena Anduze
E. Roger Mitchell
Pavlo Aldoshyn
Maryna Koshkina
Andrii Mostrenko
Roman Semysal
Roman Yasinovskyi
Oleh Shulha
Yehor Kozlov
Yevhen Chernykov
Vadym Kurylko
Antonio Banderas
Kate Bosworth
Mojean Aria
Alexis Ren
Zolee Griggs
2 Chainz
Aaron Cohen
Natalie Burn
Mark Rhino Smith
Giacomo Gianniotti
Miriam Leone
Valerio Mastandrea
Monica Bellucci
Alessio Lapice
Linda Caridi
Pier Giorgio Bellocchio
Ester Pantano
Andrea Roncato
Melissa Barrera
Jenna Ortega
Jasmin Savoy Brown
Mason Gooding
Roger Jackson
Courteney Cox
Dermot Mulroney
Jack Champion
Josh Segarra
Sam Worthington
Zoe Saldaña
Sigourney Weaver
Stephen Lang
Michelle Rodriguez
Giovanni Ribisi
Joel David Moore
CCH Pounder
Wes Studi
John Boyega
Michael Kenneth Williams
Nicole Beharie
Connie Britton
Selenis Leyva
Jeffrey Donovan
Olivia Washington
London Covington
Robb Derringer
Taron Egerton
Nikita Efremov
Sofia Lebedeva
Anthony Boyle
Toby Jones
Igor Grabuzov
Ben Miles
Ken Yamamura
Roger Allam
Adam Driver
Ariana Greenblatt
Chloe Coleman
Nika King
Brian Dare
Chris Hemsworth
Natalie Portman
Christian Bale
Tessa Thompson
Taika Waititi
Jaimie Alexander
Russell Crowe
Chris Pratt
Karen Gillan
Michael Weaver
Tim Griffin
Justin Huen
Rune Temte
Sarah Alles
Laura Sophia Becker
Ingrid Liavaag
Thea Sofie Loch Næss
Lauren LaVera
David Howard Thornton
Elliott Fullam
Sarah Voigt
Kailey Hyman
Casey Hartnett
Charlie McElveen
Amelie McLain
Johnath Davis
Keanu Reeves
Michael Nyqvist
Ian McShane
John Leguizamo
Willem Dafoe
Alfie Allen
Dean Winters
Adrianne Palicki
Lance Reddick
Tom Holland
Zendaya
Benedict Cumberbatch
Jacob Batalon
Jon Favreau
Jamie Foxx
Willem Dafoe
Alfred Molina
Benedict Wong
Jeffrey Donovan
Penelope Mitchell
Richard Brake
Kerry Knuppe
Jake Choi
Richard Fleeshman
Craige Els
Tilly Keeper
Nóra Trokán
Polina Avdeenko
Yuliya Rudina
Boris Khasanov
Yuliya Zorkina
Vasilisa Ruchimskaya
Gregory Mann
Ewan McGregor
David Bradley
Christoph Waltz
Tilda Swinton
Ron Perlman
Finn Wolfhard
Cate Blanchett
Tim Blake Nelson
Bruno Bichir
Mauricio Castillo
Marcelo Barcelo
Miguel Rodarte
Arath de la Torre
Angélica Vale
Maite Perroni
Carlos Espejel
Vadhir Derbez
Masako Nozawa
Toshio Furukawa
Yuko Minaguchi
Hiroshi Kamiya
Mamoru Miyano
Miyu Irino
Ryota Takeuchi
Aya Hisakawa
Mayumi Tanaka
Eva Green
Mark Strong
Chai Fonacier
Billie Gadsdon
Cathy Belton
Anthony Falcon
Amber Midthunder
Dakota Beavers
Michelle Thrush
Stormee Kipp
Julian Black Antelope
Dane DiLiegro
Stefany Mathias
Bennett Taylor
Mike Paterson
Kayla Adams
Matthew Holcomb
Bryan David Roberts
Chloe Berman
Brad Worch II
Eric Alperin
Cody Renee Cameron
Ben Foster
Sophie Lowe
Michael Caine
Til Schweiger
Matthew Goode
Roland Møller
William Moseley
Karel Roden
Werner Daehn
Kirsten Day
America Young
Ogie Banks
Laila Berzins
Alex Cazares
Greg Chun
Julyza Commodore
Innocent Ekakitie
Lisa Fuson
Bob Hoskins
John Leguizamo
Dennis Hopper
Samantha Mathis
Fisher Stevens
Richard Edson
Fiona Shaw
Mojo Nixon
Lance Henriksen
Sam Worthington
Matt Nable
Phoebe Tonkin
Edward Carmody
Susie Porter
Jeremy Lindsay Taylor
Sam Parsonson
Sam Cotton
George Houvardas
Chris Pratt
Bryce Dallas Howard
Laura Dern
Jeff Goldblum
Sam Neill
DeWanda Wise
Mamoudou Athie
Isabella Sermon
Campbell Scott
JP Karliak
Pierce Gagnon
Amaryllis Aubel
Jodi Benson
Alex Cazares
Kalen Chase
Ray Chase
David W. Collins
Dana Davis
Zachary Levi
Mark Strong
Asher Angel
Jack Dylan Grazer
Adam Brody
Djimon Hounsou
Faithe Herman
Meagan Good
Grace Caroline Currey
Jhon Álex Toro
Laura Acuña
Rodrigo Candamil
Felix Kammerer
Albrecht Schuch
Aaron Hilmer
Moritz Klaus
Adrian Grünewald
Edin Hasanović
Daniel Brühl
Thibault de Montalembert
Devid Striesow
David Harbour
John Leguizamo
Beverly D'Angelo
Alex Hassell
Alexis Louder
Edi Patterson
Cam Gigandet
Leah Brady
André Eriksen
Melissa Barrera
Mason Gooding
Jenna Ortega
Jack Quaid
Mikey Madison
Courteney Cox
David Arquette
Neve Campbell
Dylan Minnette
Melissa Barrera
Mason Gooding
Jenna Ortega
Jack Quaid
Mikey Madison
Courteney Cox
David Arquette
Neve Campbell
Dylan Minnette
Jonathan Majors
Glen Powell
Christina Jackson
Thomas Sadoski
Daren Kagasoff
Joe Jonas
Spencer Neville
Nick Hargrove
Boone Platt
Viola Davis
Thuso Mbedu
Lashana Lynch
Sheila Atim
John Boyega
Jordan Bolger
Hero Fiennes Tiffin
Jimmy Odukoya
Masali Baduza
Lily Sullivan
Alyssa Sutherland
Morgan Davies
Nell Fisher
Gabrielle Echols
Mia Challis
Jayden Daniels
Tai Wano
Billy Reynolds-McCarthy
Kiana Madeira
Ross Butler
Matthew Noszka
Bree Winslow
Nicholas Duvernay
Manu Bennett
Ryan Bown
Poppy Gilbert
Cecilia Diesch
Egor Koreshkov
Alena Konstantinova
Konstantin Samoukov
Pyotr Romanov
Nikita Dyuvbanov
Liza Martines
Viktor Potapeshkin
Dmitry Frid
Katerina Shpitsa
Benedict Cumberbatch
Elizabeth Olsen
Chiwetel Ejiofor
Benedict Wong
Xochitl Gomez
Jett Klyne
Julian Hilliard
Sheila Atim
Adam Hugill
José María Yázpik
Shannyn Sossamon
Tommy Flanagan
Ron Perlman
Karla Souza
Tim Roth
Paz Vega
Neal McDonough
Keidrich Sellati
Robert Downey Jr.
Chris Hemsworth
Mark Ruffalo
Chris Evans
Scarlett Johansson
Benedict Cumberbatch
Tom Holland
Chadwick Boseman
Don Cheadle
Sosie Bacon
Kyle Gallner
Caitlin Stasey
Jessie T. Usher
Kal Penn
Rob Morgan
Robin Weigert
Judy Reyes
Gillian Zinser
Damián Alcázar
Alfonso Herrera
Joaquín Cosío
Ana de la Reguera
Ana Martín
Angelina Peláez
Mayra Hermosillo
Fermín Martínez
Leticia Huijara
Bruce Willis
Jack Kilmer
Lochlyn Munro
Jimmy Jean-Louis
Willow Shields
Dina Meyer
Timothy V. Murphy
Lorenzo Antonucci
Joe Munroe
Jake Gyllenhaal
Dennis Quaid
Jaboukie Young-White
Gabrielle Union
Lucy Liu
Alan Tudyk
Jonathan Melo
Abraham Benrubi
Karan Soni
Charlton Heston
Yul Brynner
Anne Baxter
Edward G. Robinson
Yvonne De Carlo
Debra Paget
John Derek
Cedric Hardwicke
Nina Foch
Charlton Heston
Yul Brynner
Anne Baxter
Edward G. Robinson
Yvonne De Carlo
Debra Paget
John Derek
Cedric Hardwicke
Nina Foch
Natsuki Hanae
Akari Kito
Takahiro Sakurai
Hochu Otsuka
Yuki Kaji
Ai Kakuma
Daisuke Namikawa
Toshihiko Seki
Takehito Koyasu
Blanca Suárez
Alberto San Juan
Rubén Cortada
Ernesto Alterio
Carlos Areces
Isidro Montalvo
Jaime Ordóñez
Enrique Villén
Pat Aguiló
Pierre Coffin
Steve Carell
Russell Brand
Alan Arkin
Taraji P. Henson
Jean-Claude Van Damme
Lucy Lawless
Dolph Lundgren
Danny Trejo
Michael B. Jordan
Sylvester Stallone
Tessa Thompson
Wood Harris
Russell Hornsby
Phylicia Rashād
Dolph Lundgren
Florian Munteanu
Andre Ward
Michael B. Jordan
Sylvester Stallone
Tessa Thompson
Phylicia Rashād
Andre Ward
Tony Bellew
Ritchie Coster
Jacob 'Stitch' Duran
Graham McTavish
Idris Elba
Leah Sava Jeffries
Iyana Halley
Sharlto Copley
Martin Munro
Liyabuya Gongo
Daniel Hadebe
Thapelo Sebogodi
Mduduzi Mavimbela
Vin Diesel
Michelle Rodriguez
Tyrese Gibson
Ludacris
Jason Momoa
Nathalie Emmanuel
Jordana Brewster
John Cena
Jason Statham
Alessandro Gassmann
Ginevra Francesconi
Remo Girone
Alessio Praticò
Francesco Villano
Gabriele Falsetta
Marcello Mazzarella
Mauro Lamanna
Sinja Dieks
Jason Statham
Holt McCallany
Josh Hartnett
Scott Eastwood
Darrell D'Silva
Babs Olusanmokun
Jeffrey Donovan
Eddie Marsan
Andy García
Sydney Craven
Imran Adams
Jarreau Benjamin
Matt Barkley
Peter Brooke
Ocean Navarro
Gary Graham
Gabriel Freilich
Terry Bird
Rosalie Chiang
Sandra Oh
Ava Morse
Hyein Park
Maitreyi Ramakrishnan
Orion Lee
Wai Ching Ho
Tristan Allerick Chen
Lori Tan Chinn
Stephanie Beatriz
María Cecilia Botero
John Leguizamo
Mauro Castillo
Jessica Darrow
Angie Cepeda
Carolina Gaitán
Diane Guerrero
Wilmer Valderrama
James Cromwell
Darcey Ewart
Sarah-Jane Potts
Aaron McCusker
Joseph Millson
Stephanie Levi-John
Florisa Kamara
Lucas Persaud
Jessica Blake
Channing Tatum
Salma Hayek
Ayub Khan-Din
Jemelia George
Ethan Lawrence
Juliette Motamed
Alan Cox
Caitlin Gerard
Vicki Pepperdine
Shawn Mendes
Javier Bardem
Winslow Fegley
Constance Wu
Scoot McNairy
Brett Gelman
Ego Nwodim
Lyric Hurd
Jason Kravits
Kevin Sorbo
James Russo
Major Dodge
Stelio Savante
Krista Bradley
Xiomara Bermudez
Jay Giannone
Charles "Skeeta" Jenkins
Major Dodge Jr.
Andrew Garfield
Sam Worthington
Vince Vaughn
Teresa Palmer
Luke Bracey
Hugo Weaving
Ryan Corr
Rachel Griffiths
Richard Roxburgh
Ester Expósito
Ángela Cremonte
Inés Fernández
Magüi Mira
Aten Soria
María José Sarrate
Sofía Reyes
Fernando Valdivielso
Federico Aguado
Nick Blood
Emm Wiseman
Paul Kaye
Allan Corduner
Daniel Ben Zenou
Sofia Weldon
Anton Trendafilov
Meglena Karalambova
Jonathan Yunger
Megumi Ogata
Kana Hanazawa
Yuichi Nakamura
Takahiro Sakurai
Mikako Komatsu
Koki Uchiyama
Tomokazu Seki
Mitsuo Iwata
Takaya Kuroda
Robert Pattinson
Zoë Kravitz
Paul Dano
Jeffrey Wright
John Turturro
Peter Sarsgaard
Andy Serkis
Colin Farrell
Jayme Lawson
Jaden Smith
Cara Delevingne
Cuba Gooding Jr.
Nia Long
RZA
JT Neal
Chris D'Elia
Harper Gunn
Dan Tymon
Toru Furuya
Yu Mizushima
Mami Yamase
Akiko Wada
Yuriko Yamamoto
Kōhei Miyauchi
Shigeru Chiba
Hiroko Emori
Hiroko Maruyama
Georgie Henley
Skandar Keynes
William Moseley
Anna Popplewell
Tilda Swinton
James McAvoy
Jim Broadbent
Kiran Shah
James Cosmo
Will Beinbrink
María Gabriela de Faría
Irán Castillo
Joseph Marcell
Hector Kotsifakis
Juan Ignacio Aranda
Evelia Di Gennaro
Thomas Hobson
Tara Perry
Phil Morris
Angela Bettis
David Arquette
Tim Blake Nelson
Joseph Ruud
David Aaron Baker
Neva Howell
Gilles Lellouche
Joanna Kulig
Mikhail Gorevoy
Sasha Piltsin
Mikhail Safronov
Aleksey Gorbunov
Igor Jijikine
Elisa Lasowski
Daniil Vorobyov
Malena Villa
Julio Perillán
Ailín Salas
Rafael Federman
Lina Gorbaneva
David Schetman
Ernestina Gatti
Lucas Damario
Eva Bianco
Matt Damon
Ben Affleck
Jason Bateman
Marlon Wayans
Chris Messina
Chris Tucker
Viola Davis
Julius Tennon
Damian Young
Amy Adams
Patrick Dempsey
Maya Rudolph
Gabriella Baldacchino
James Marsden
Idina Menzel
Yvette Nicole Brown
Jayma Mays
Kolton Stewart
Eva Noblezada
Simon Pegg
Jane Fonda
Whoopi Goldberg
Flula Borg
Lil Rel Howery
Colin O'Donoghue
John Ratzenberger
Adelynn Spoon
Brad Pitt
Joey King
Aaron Taylor-Johnson
Brian Tyree Henry
Andrew Koji
Hiroyuki Sanada
Michael Shannon
Bad Bunny
Sandra Bullock
Joshua Bassett
Thomas Lennon
Joseph Kamal
Akmal Saleh
Steve Zahn
Jack Whitehall
Kieran Sequoia
Alice Isaaz
Jamie Demetriou
Anna Akana
Mark Dacascos
Teresa Ting
Dustin Nguyen
Dan Southworth
Yoshi Sudarso
Akira Koieyama
Niino Furuhata
Luna Fujimoto
Matthew McConaughey
Reese Witherspoon
Scarlett Johansson
Taron Egerton
Bobby Cannavale
Tori Kelly
Nick Kroll
Halsey
Spike Jonze
Holly Earl
Maxime Durand
Catherine Hannay
Jack Trueman
Joshua Takacs
Manuel Cauchi
Malachi Pullar-Latchman
Thomas Michael Flynn
Mike Myers
Eddie Murphy
Cameron Diaz
John Lithgow
Vincent Cassel
Peter Dennis
Clive Pearse
Jim Cummings
Bobby Block

TypeError: 'float' object is not subscriptable

## Investigação do dataset

In [ ]:
data_max =  df['data'].max()
data_min =  df['data'].min()

print(f"A data mínima contida no datast é {data_min} e a data máxima é {data_max}")

A data mínima contida no datast é 1903-05-15 00:00:00 e a data máxima é 2023-12-31 00:00:00

In [ ]:
df[df['orig_title'].str.contains('.Trap.')]

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country,data_editada,data,elenco_lista
1648,Puss in Book: Trapped in an Epic Tale,06/20/2017,66.0,"Family, Fantasy, Animation, Comedy, Adventure","After tumbling into a magic storybook, Puss in...","Eric Bauza, Puss In Boots / Eames / Princess M...",Puss in Book: Trapped in an Epic Tale,Released,English,111000000.0,347509904.0,US,06/20/2017,2017-06-20,"[Eric Bauza, Puss In Boots / Eames / Princess ..."
4979,JLA Adventures: Trapped in Time,01/21/2014,67.0,"Family, Animation, Action, Science Fiction",Get ready for a battle of the ages when the Ju...,"Diedrich Bader, Batman / Bruce Wayne / Narrato...",JLA Adventures: Trapped in Time,Released,English,178000000.0,437664915.2,US,01/21/2014,2014-01-21,"[Diedrich Bader, Batman / Bruce Wayne / Narrat..."

In [ ]:
df[df['data'] == data_min]

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country,data_editada,data,elenco_lista
558,The Life and Passion of Jesus Christ,05/15/1903,63.0,"Drama, History","The story of Jesus Christ, from the proclamati...","Madame Moreau, Virgin Mary, Monsieur Moreau, J...",La vie et la passion de Jésus Christ,Released,French,106400000.0,524759370.4,FR,05/15/1903,1903-05-15,"[Madame Moreau, Virgin Mary, Monsieur Moreau, ..."

In [ ]:
df[df['orig_title'].str.contains('Cinderela')]

Empty DataFrame
Columns: [names, date_x, score, genre, overview, crew, orig_title, status, orig_lang, budget_x, revenue, country, data_editada, data, elenco_lista]
Index: []

In [ ]:
df_1987 = df[df['data'].between('1987-1-1', '1987-12-31')]
df_1987[df_1987['orig_lang'] == 'Portuguese'].sort_values(by='data')

Empty DataFrame
Columns: [names, date_x, score, genre, overview, crew, orig_title, status, orig_lang, budget_x, revenue, country, data_editada, data, elenco_lista]
Index: []

In [ ]:
df_1987 = df[df['data'].between('1987-1-1', '1987-12-31')]
df_1987[~(df_1987['orig_lang'] == 'English')].sort_values(by='data')

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country,data_editada,data,elenco_lista
7855,Bizarre,01/16/1987,46.0,"Drama, Thriller",A wife escapes her pressure-filled marriage on...,"Florence Guérin, Laurie / Lorenza, Luciano Bar...",Profumo,Released,Italian,74000000.0,8.985384e+08,IT,01/16/1987,1987-01-16,"[Florence Guérin, Laurie / Lorenza, Luciano Ba..."
8821,El día de los albañiles 3,01/30/1987,70.0,Comedy,We don't have an overview translated in Englis...,"Alfonso Zayas, , Angélica Chain, Beatriz / Jul...",El día de los albañiles 3,Released,"Spanish, Castilian",95240000.0,5.700861e+08,MX,01/30/1987,1987-01-30,"[Alfonso Zayas, , Angélica Chain, Beatriz / Ju..."
583,Exploits of a Young Don Juan,03/11/1987,57.0,"Comedy, Drama",Roger is a 16-year-old who seeks to lose his v...,"Fabrice Josso, Roger, Serena Grandi, Ursule, C...",Les Exploits d'un jeune Don Juan,Released,French,59400000.0,4.482881e+08,FR,03/11/1987,1987-03-11,"[Fabrice Josso, Roger, Serena Grandi, Ursule, ..."
6335,"Eleven Days, Eleven Nights",03/27/1987,47.0,"Drama, Romance","In eleven days time, Michael is due to wed his...","Jessica Moore, Sarah Asproon, Joshua McDonald,...","Undici giorni, undici notti",Released,Italian,129200000.0,9.474687e+08,IT,03/27/1987,1987-03-27,"[Jessica Moore, Sarah Asproon, Joshua McDonald..."
7935,Los verduleros 2,07/02/1987,65.0,Comedy,Two police officers decide to open a police ac...,"Alfonso Zayas, Roberto, Lina Santos, Rocío, Lu...",Los verduleros 2,Released,"Spanish, Castilian",100000000.0,2.463671e+08,MX,07/02/1987,1987-07-02,"[Alfonso Zayas, Roberto, Lina Santos, Rocío, L..."
1834,Saint Seiya: Evil Goddess Eris,07/18/1987,71.0,"Action, Animation, Fantasy","When Seiya, Hyōga and Shun visit Saori (Athena...","Toru Furuya, Seiya (voice), Hirotaka Suzuoki, ...",聖闘士星矢,Released,Japanese,82840000.0,2.489340e+08,JP,07/18/1987,1987-07-18,"[Toru Furuya, Seiya (voice), Hirotaka Suzuoki,..."
2387,Dragon Ball: Sleeping Princess in Devil's Castle,07/18/1987,65.0,"Action, Animation",Goku and Kuririn are given an assignment by Ka...,"Mayumi Tanaka, Kuririn, Nachi Nozawa, Lucifer,...",ドラゴンボール 魔神城のねむり姫,Released,Japanese,82600000.0,3.073904e+08,JP,07/18/1987,1987-07-18,"[Mayumi Tanaka, Kuririn, Nachi Nozawa, Lucifer..."
2873,Za gyakutai: Nyotai ikedori-hen,07/18/1987,65.0,NaN,We don't have an overview translated in Englis...,"Azusa Nakagawa, , Yûko Fujishiro, , Kaori Haru...",ザ・虐待 女体いけどり篇,Released,Japanese,38600000.0,5.422332e+08,JP,07/18/1987,1987-07-18,"[Azusa Nakagawa, , Yûko Fujishiro, , Kaori Har..."
8369,A Chinese Ghost Story,07/18/1987,73.0,"Fantasy, Action","Ning Tsai-Shen, a humble tax collector, arrive...","Leslie Cheung, Ling Choi Sin, Joey Wong, Lip S...",倩女幽魂,Released,Cantonese,1250000.0,7.184248e+07,HK,07/18/1987,1987-07-18,"[Leslie Cheung, Ling Choi Sin, Joey Wong, Lip ..."
7419,Hachiko,08/01/1987,76.0,"Drama, Family","The tragic, true story about Hachikō, an Akita...","Tatsuya Nakadai, Shujiro Ueno, Kaoru Yachigusa...",ハチ公物語,Released,Japanese,104600000.0,3.634544e+08,JP,08/01/1987,1987-08-01,"[Tatsuya Nakadai, Shujiro Ueno, Kaoru Yachigus..."
7315,Project A: Part II,08/19/1987,71.0,"Action, Comedy",Dragon is now transferred to be the police hea...,"Jackie Chan, Sgt. Dragon Ma Yue-Lung, Maggie C...",A計劃續集,Released,Cantonese,173000000.0,3.876316e+08,HK,08/19/1987,1987-08-19,"[Jackie Chan, Sgt. Dragon Ma Yue-Lung, Maggie ..."
2389,Yu Pui Tsuen II,10/01/1987,62.0,"Drama, Fantasy, Romance",Before Michael Mak’s Sex And Zen became a cult...,"Cheng Yuen-Man, , Chung-Sing Choh, , Choh Chun...",浮世風情繪,Released,Cantonese,84000000.0,1.014981e+09,HK,10/01/1987,1987-10-01,"[Cheng Yuen-Man, , Chung-Sing Choh, , Choh Chu..."

In [ ]:
df[df['orig_title'].str.contains('Cidade')]

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country,data_editada,data,elenco_lista
2113,City of God,08/30/2002,84.0,"Drama, Crime","In the slums of Rio, two kids' paths diverge a...","Alexandre Rodrigues, Buscapé, Leandro Firmino,...",Cidade de Deus,Released,Portuguese,3300000.0,30641770.0,AU,08/30/2002,2002-08-30,"[Alexandre Rodrigues, Buscapé, Leandro Firmino..."

In [ ]:
df[df['names'].str.contains('Eraser')]

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country,data_editada,data,elenco_lista
5120,Eraser,09/19/1996,60.0,"Action, Drama, Mystery, Thriller",U.S. Marshall John Kruger erases the identitie...,"Arnold Schwarzenegger, U.S. Marshal John 'The ...",Eraser,Released,English,100000000.0,234400000.0,AU,09/19/1996,1996-09-19,"[Arnold Schwarzenegger, U.S. Marshal John 'The..."
7740,Eraserhead,01/01/1980,74.0,"Fantasy, Horror",First time father Henry Spencer tries to survi...,"Jack Nance, Henry Spencer, Charlotte Stewart, ...",Eraserhead,Released,English,100000.0,7097971.0,AU,01/01/1980,1980-01-01,"[Jack Nance, Henry Spencer, Charlotte Stewart,..."
9217,Eraser: Reborn,06/07/2022,66.0,"Action, Crime, Thriller",U.S. Marshal Mason Pollard specializes in “era...,"Dominic Sherwood, U.S. Marshal Mason Pollard, ...",Eraser: Reborn,Released,English,101000000.0,321357348.6,US,06/07/2022,2022-06-07,"[Dominic Sherwood, U.S. Marshal Mason Pollard,..."

In [ ]:
df[df['names'].str.contains('Room')]

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country,data_editada,data,elenco_lista
423,Wire Room,09/02/2022,66.0,"Action, Crime, Thriller",New recruit Justin Rosa must monitor arms-smug...,"Kevin Dillon, Justin Rosa, Bruce Willis, Shane...",Wire Room,Released,English,101000000.0,321357348.6,US,09/02/2022,2022-09-02,"[Kevin Dillon, Justin Rosa, Bruce Willis, Shan..."
1034,War Room,08/28/2015,78.0,"Drama, Romance",The family-friendly movie explores the transfo...,"Karen Abercrombie, Clara Williams, Priscilla C...",War Room,Released,English,3000000.0,73989734.0,US,08/28/2015,2015-08-28,"[Karen Abercrombie, Clara Williams, Priscilla ..."
1238,The Immaculate Room,11/01/2022,56.0,"Mystery, Thriller, Drama, Science Fiction","Mike and Kate, a young couple, get the once-in...","Kate Bosworth, Kate, Emile Hirsch, Michael, As...",The Immaculate Room,Released,English,109200000.0,260090578.4,AU,11/01/2022,2022-11-01,"[Kate Bosworth, Kate, Emile Hirsch, Michael, A..."
1663,Escape Room: Tournament of Champions,07/01/2021,67.0,"Horror, Thriller, Mystery",Six people unwittingly find themselves locked ...,"Taylor Russell, Zoey Davis, Logan Miller, Ben ...",Escape Room: Tournament of Champions,Released,English,15000000.0,53493064.0,AU,07/01/2021,2021-07-01,"[Taylor Russell, Zoey Davis, Logan Miller, Ben..."
2053,Delicious Room Salon Service 2,09/30/2019,52.0,Romance,We don't have an overview translated in Englis...,"이미선, , Min Jung, , Kim Soo-ji,",룸싸롱 : 맛있는 서비스2,Released,Korean,136400000.0,328929749.2,KR,09/30/2019,2019-09-30,"[이미선, , Min Jung, , Kim Soo-ji, ]"
2464,Escape Room,02/07/2019,65.0,"Horror, Thriller, Mystery",Six strangers find themselves in circumstances...,"Taylor Russell, Zoey Davis, Logan Miller, Ben ...",Escape Room,Released,English,9000000.0,155615727.0,AU,02/07/2019,2019-02-07,"[Taylor Russell, Zoey Davis, Logan Miller, Ben..."
2743,Delicious Room Salon Service,08/09/2018,68.0,Romance,A room salon isn't doing well. There's only Mi...,"Kim Hee-jeong, Joo-hee, Yoon Da-hyun, Min-joo,...",룸싸롱 맛있는 서비스,Released,Korean,78200000.0,360564423.2,KR,08/09/2018,2018-08-09,"[Kim Hee-jeong, Joo-hee, Yoon Da-hyun, Min-joo..."
3276,Room in Rome,05/07/2010,64.0,"Drama, Romance",A hotel room in the center of Rome serves as t...,"Elena Anaya, Alba, Natasha Yarovenko, Natasha,...",Habitación en Roma,Released,"Spanish, Castilian",36345000.0,844281.0,ES,05/07/2010,2010-05-07,"[Elena Anaya, Alba, Natasha Yarovenko, Natasha..."
3928,Room Salon College Girls,03/29/2018,0.0,Romance,Sexy female college students get part-time job...,"Kim Hee-jeong, , Yoon Da-hyun, , Choi Chul-min,",룸싸롱 여대생들,Released,Korean,181600000.0,175269998.8,KR,03/29/2018,2018-03-29,"[Kim Hee-jeong, , Yoon Da-hyun, , Choi Chul-mi..."
4079,The Room,11/06/2019,64.0,"Horror, Drama, Mystery, Science Fiction",Kate and Matt discover that a part of their ho...,"Olga Kurylenko, Kate, Kevin Janssens, Matt, Fr...",The Room,Released,English,39412225.8,44291.0,BE,11/06/2019,2019-11-06,"[Olga Kurylenko, Kate, Kevin Janssens, Matt, F..."
4239,There Is a Japanese Woman in My Room,02/12/2019,47.0,"Drama, Romance",A determined Japanese woman gets a job in Kore...,"Mao Hamasaki, Sakura / Kento, Shin Yeon-woo, M...",내방에 일본여자가 있다,Released,Korean,129200000.0,947468745.8,KR,02/12/2019,2019-02-12,"[Mao Hamasaki, Sakura / Kento, Shin Yeon-woo, ..."
4503,Escape Room,08/31/2017,49.0,"Horror, Thriller, Fantasy",Four friends who partake in a popular Los Ange...,"Skeet Ulrich, Brice, Sean Young, Ramona, Chris...",Escape Room,Released,English,9000000.0,155615727.0,RU,08/31/2017,2017-08-31,"[Skeet Ulrich, Brice, Sean Young, Ramona, Chri..."
4732,Room,01/15/2016,80.0,"Drama, Thriller","Held captive for 7 years in an enclosed space,...","Brie Larson, Joy ""Ma"" Newsome, Jacob Tremblay,...",Room,Released,English,13000000.0,36316727.0,GB,01/15/2016,2016-01-15,"[Brie Larson, Joy ""Ma"" Newsome, Jacob Tremblay..."
4967,Panic Room,04/11/2002,67.0,"Crime, Drama, Thriller",Trapped in their New York brownstone's panic r...,"Jodie Foster, Meg Altman, Kristen Stewart, Sar...",Panic Room,Released,English,48000000.0,196308367.0,AU,04/11/2002,2002-04-11,"[Jodie Foster, Meg Altman, Kristen Stewart, Sa..."
5425,Room Salon College Girls 3,04/17/2020,50.0,"Romance, Action","Hee-jung, a college student, uses up a lot of ...","Kim Ji-ah, , Jin Yi, , Hae Il, , Min Do-yoon, ...",룸싸롱 여대생들 3,Released,Korean,140400000.0,597705817.6,KR,04/17/2020,2020-04-17,"[Kim Ji-ah, , Jin Yi, , Hae Il, , Min Do-yoon,..."
5436,Escape Room,09/14/2017,45.0,"Horror, Thriller",Six friends test their intelligence in a game ...,"Evan Williams, Tyler, Annabelle Stephenson, Na...",Escape Room,Released,English,9000000.0,155615727.0,RU,09/14/2017,2017-09-14,"[Evan Williams, Tyler, Annabelle Stephenson, N..."
6461,Four Rooms,03/28/1996,58.0,"Crime, Comedy",It's Ted the Bellhop's first night on the job....,"Tim Roth, Ted the Bellhop, Jennifer Beals, Ang...",Four Rooms,Released,English,4000000.0,4301000.0,AU,03/28/1996,1996-03-28,"[Tim Roth, Ted the Bellhop, Jennifer Beals, An..."
8665,Green Room,05/12/2016,67.0,"Horror, Crime, Thriller",A punk rock band becomes trapped in a secluded...,"Anton Yelchin, Pat, Imogen Poots, Amber, Alia ...",Green Room,Released,English,5000000.0,3807503.0,AU,05/12/2016,2016-05-12,"[Anton Yelchin, Pat, Imogen Poots, Amber, Alia..."
8908,The Roommate,02/04/2011,54.0,"Thriller, Drama, Horror","When Sara, a young design student from Iowa, a...","Leighton Meester, Rebecca Evans, Minka Kelly, ...",The Roommate,Released,English,16000000.0,52545707.0,US,02/04/2011,2011-02-04,"[Leighton Meester, Rebecca Evans, Minka Kelly,..."
9734,Marvin's Room,12/18/1996,67.0,Drama,A leukemia patient attempts to end a 20-year f...,"Meryl Streep, Lee Wakefield Lacker, Diane Keat...",Marvin's Room,Released,English,23000000.0,12803305.0,US,12/18/1996,1996-12-18,"[Meryl Streep, Lee Wakefield Lacker, Diane Kea..."
10084,Fermat's Room,10/07/2007,66.0,"Mystery, Thriller",Four mathematicians who do not know each other...,"Lluís Homar, Hilbert, Santi Millán, Pascal, Al...",La Habitación de Fermat,Released,"Spanish, Castilian",118154097.6,661906631.6,ES,10/07/2007,2007-10-07,"[Lluís Homar, Hilbert, Santi Millán, Pascal, A..."

In [ ]:
df[df['names'].str.contains("Girlfriend's")]

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country,data_editada,data,elenco_lista
1297,My Girlfriend's Mother 2,08/30/2018,22.0,Romance,Young Se-hee gets married to middle aged Min-g...,"Yoo Ni, , Lee Chae-dam, , Lee Joon-hyuk-II, , ...",여친 엄마2,Released,Korean,12001040.0,38139010.0,KR,08/30/2018,2018-08-30,"[Yoo Ni, , Lee Chae-dam, , Lee Joon-hyuk-II, ,..."
5533,My Girlfriend's Mother 3,03/22/2019,10.0,"Romance, Drama",The man was originally very loving with his gi...,"Baek Se-ri, , Ahn So-hee,",여친 엄마 3,Released,Korean,198540000.0,38157314.0,CN,03/22/2019,2019-03-22,"[Baek Se-ri, , Ahn So-hee, ]"
9411,My Girlfriend's Mother,07/06/2017,60.0,"Romance, Drama",Kyeong-joon is driven out to the streets as he...,"Si Woo, Kyeong-joon, Ahn So-hee, Ji-hye, Min J...",여친 엄마,Released,Korean,73000000.0,544378189.4,KR,07/06/2017,2017-07-06,"[Si Woo, Kyeong-joon, Ahn So-hee, Ji-hye, Min ..."

In [ ]:
df['crew'][0]

"Michael B. Jordan, Adonis Creed, Tessa Thompson, Bianca Taylor, Jonathan Majors, Damien Anderson, Wood Harris, Tony 'Little Duke' Evers, Phylicia Rashād, Mary Anne Creed, Mila Davis-Kent, Amara Creed, Florian Munteanu, Viktor Drago, José Benavidez Jr., Felix Chavez, Selenis Leyva, Laura Chavez"