In [165]:
import pandas as pd
import numpy as np

In [166]:
df = pd.read_csv('https://raw.githubusercontent.com/ClaudiaSobral/treinamento-dados-end-to-end/refs/heads/main/data/silver/imdb_movies_segmentado.csv')

In [167]:
df['score'].max()

np.float64(100.0)

In [168]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6245 entries, 0 to 6244
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   names         6245 non-null   str
 1   date_x        6245 non-null   str
 2   score         6245 non-null   float64
 3   genre         6195 non-null   str
 4   overview      6245 non-null   str
 5   crew          6201 non-null   str
 6   orig_title    6245 non-null   str
 7   status        6245 non-null   str
 8   orig_lang     6245 non-null   str
 9   budget_x      6245 non-null   float64
 10  revenue       6245 non-null   float64
 11  country       6245 non-null   str
 12  data_editada  6245 non-null   str
 13  data          6245 non-null   str
 14  elenco_lista  6201 non-null   str
dtypes: float64(3), str(12)
memory usage: 6.0 MB

In [169]:
df = df.dropna()

In [170]:
df.isnull().sum()

names           0
date_x          0
score           0
genre           0
overview        0
crew            0
orig_title      0
status          0
orig_lang       0
budget_x        0
revenue         0
country         0
data_editada    0
data            0
elenco_lista    0
dtype: int64

In [171]:
filtro_estrelas = [
    (df['score'] <=20.0),
    (df['score'] > 20.0) & (df['score'] <=40.0),
    (df['score'] > 40.0) & (df['score'] <=60.0),
    (df['score'] > 60.0) & (df['score'] <=80.0),
    (df['score'] <=100.0)
]

categoria_estrelas = ["1", "2", "3", "4", "5"]

In [172]:
df['estrelas'] = np.select(filtro_estrelas, categoria_estrelas, default="0")
df.head()

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country,data_editada,data,elenco_lista,estrelas
0,Creed III,03/02/2023,73.0,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,Released,English,75000000.0,2.716167e+08,AU,03/02/2023,2023-03-02,"['Michael B. Jordan', 'Adonis Creed', 'Tessa T...",4
1,Avatar: The Way of Water,12/15/2022,78.0,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU,12/15/2022,2022-12-15,"['Sam Worthington', 'Jake Sully', 'Zoe Saldaña...",4
2,The Super Mario Bros. Movie,04/05/2023,76.0,"Animation, Adventure, Family, Fantasy, Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",The Super Mario Bros. Movie,Released,English,100000000.0,7.244590e+08,AU,04/05/2023,2023-04-05,"['Chris Pratt', 'Mario (voice)', 'Anya Taylor-...",4
3,Mummies,01/05/2023,70.0,"Animation, Comedy, Family, Adventure, Fantasy","Through a series of unfortunate events, three ...","Óscar Barberán, Thut (voice), Ana Esther Albor...",Momias,Released,"Spanish, Castilian",12300000.0,3.420000e+07,AU,01/05/2023,2023-01-05,"['Óscar Barberán', 'Thut (voice)', 'Ana Esther...",4
4,Supercell,03/17/2023,61.0,Action,Good-hearted teenager William always lived in ...,"Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...",Supercell,Released,English,77000000.0,3.409420e+08,US,03/17/2023,2023-03-17,"['Skeet Ulrich', 'Roy Cameron', 'Anne Heche', ...",4

In [173]:
df = df.drop(columns=['elenco_lista', 'date_x'])

In [174]:
df['margem_de_lucro'] = ((df['revenue'] - df['budget_x'])/ df['revenue']) * 100

In [175]:
df['roi'] = df['revenue'] / df['budget_x']
df.head()

,names,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country,data_editada,data,estrelas,margem_de_lucro,roi
0,Creed III,73.0,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,Released,English,75000000.0,2.716167e+08,AU,03/02/2023,2023-03-02,4,72.387556,3.621556
1,Avatar: The Way of Water,78.0,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU,12/15/2022,2022-12-15,4,80.144984,5.036511
2,The Super Mario Bros. Movie,76.0,"Animation, Adventure, Family, Fantasy, Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",The Super Mario Bros. Movie,Released,English,100000000.0,7.244590e+08,AU,04/05/2023,2023-04-05,4,86.196597,7.244590
3,Mummies,70.0,"Animation, Comedy, Family, Adventure, Fantasy","Through a series of unfortunate events, three ...","Óscar Barberán, Thut (voice), Ana Esther Albor...",Momias,Released,"Spanish, Castilian",12300000.0,3.420000e+07,AU,01/05/2023,2023-01-05,4,64.035088,2.780488
4,Supercell,61.0,Action,Good-hearted teenager William always lived in ...,"Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...",Supercell,Released,English,77000000.0,3.409420e+08,US,03/17/2023,2023-03-17,4,77.415511,4.427818

In [176]:
df[df['roi'] < 1]

,names,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country,data_editada,data,estrelas,margem_de_lucro,roi
32,13 Exorcisms,55.0,"Drama, Horror","After participating in a séance, young Laura b...","María Romanillos, Laura, Ruth Díaz, Carmen, Ur...",13 exorcismos,Released,"Spanish, Castilian",2480000.0,1891519.0,ES,11/04/2022,2022-11-04,3,-31.111556,0.762709
37,Shotgun Wedding,63.0,"Action, Comedy, Romance",Darcy and Tom gather their families for the ul...,"Jennifer Lopez, Darcy, Josh Duhamel, Tom, Jenn...",Shotgun Wedding,Released,English,16050000.0,4495365.0,AU,01/26/2023,2023-01-26,4,-257.034412,0.280085
46,Roald Dahl's Matilda the Musical,68.0,"Family, Comedy, Fantasy",An extraordinary young girl discovers her supe...,"Alisha Weir, Matilda Wormwood, Emma Thompson, ...",Roald Dahl's Matilda the Musical,Released,English,25000000.0,13276499.0,AU,12/08/2022,2022-12-08,4,-88.302654,0.531060
53,Champions,68.0,Comedy,A stubborn and hotheaded minor league basketba...,"Woody Harrelson, Marcus, Kaitlin Olson, Alex, ...",Champions,Released,English,51880004.0,9263009.0,AU,03/09/2023,2023-03-09,4,-460.077228,0.178547
64,Diabolik - Ginko Attacks,57.0,"Crime, Action",Diabolik nearly gets caught in Inspector Ginko...,"Giacomo Gianniotti, Diabolik, Miriam Leone, Ev...",Diabolik - Ginko all'attacco!,Released,Italian,21680000.0,1228459.0,IT,11/17/2022,2022-11-17,3,-1664.812664,0.056663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6226,Last Knights,65.0,"Action, Adventure","When an evil emperor executes their leader, hi...","Clive Owen, Raiden, Morgan Freeman, Bartok, Ak...",Last Knights,Released,English,40000000.0,3643591.0,AU,05/27/2015,2015-05-27,4,-997.818059,0.091090
6230,My Student's Mom 2,10.0,Romance,"Jong-min, a tutor, keeps attracting attention ...","Kim In-ae, , Choi Woo-suk-I, , Park Hyun-jung,...",내 학생의 엄마 2,Released,Korean,201940000.0,38157314.0,KR,11/09/2017,2017-11-09,1,-429.230123,0.188954
6234,Perfect Sense,69.0,"Drama, Science Fiction, Romance","In Glasgow, Scotland, while a mysterious pande...","Ewan McGregor, Michael, Eva Green, Susan, Ewen...",Perfect Sense,Released,English,12200120.0,138868.0,GB,10/07/2011,2011-10-07,4,-8685.407725,0.011383
6238,Metallica: Through the Never,68.0,Music,"Trip, a young roadie for Metallica, is sent on...","Dane DeHaan, Trip, James Hetfield, Himself, La...",Metallica: Through the Never,Released,English,18000000.0,7972967.0,AU,12/02/2013,2013-12-02,4,-125.762881,0.442943
6241,Marshall,73.0,Drama,"Thurgood Marshall, the first African-American ...","Chadwick Boseman, Thurgood Marshall, Josh Gad,...",Marshall,Released,English,12000000.0,10116816.0,AU,06/07/2020,2020-06-07,4,-18.614394,0.843068

In [177]:
df[df['margem_de_lucro'] < 0]

,names,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country,data_editada,data,estrelas,margem_de_lucro,roi
32,13 Exorcisms,55.0,"Drama, Horror","After participating in a séance, young Laura b...","María Romanillos, Laura, Ruth Díaz, Carmen, Ur...",13 exorcismos,Released,"Spanish, Castilian",2480000.0,1891519.0,ES,11/04/2022,2022-11-04,3,-31.111556,0.762709
37,Shotgun Wedding,63.0,"Action, Comedy, Romance",Darcy and Tom gather their families for the ul...,"Jennifer Lopez, Darcy, Josh Duhamel, Tom, Jenn...",Shotgun Wedding,Released,English,16050000.0,4495365.0,AU,01/26/2023,2023-01-26,4,-257.034412,0.280085
46,Roald Dahl's Matilda the Musical,68.0,"Family, Comedy, Fantasy",An extraordinary young girl discovers her supe...,"Alisha Weir, Matilda Wormwood, Emma Thompson, ...",Roald Dahl's Matilda the Musical,Released,English,25000000.0,13276499.0,AU,12/08/2022,2022-12-08,4,-88.302654,0.531060
53,Champions,68.0,Comedy,A stubborn and hotheaded minor league basketba...,"Woody Harrelson, Marcus, Kaitlin Olson, Alex, ...",Champions,Released,English,51880004.0,9263009.0,AU,03/09/2023,2023-03-09,4,-460.077228,0.178547
64,Diabolik - Ginko Attacks,57.0,"Crime, Action",Diabolik nearly gets caught in Inspector Ginko...,"Giacomo Gianniotti, Diabolik, Miriam Leone, Ev...",Diabolik - Ginko all'attacco!,Released,Italian,21680000.0,1228459.0,IT,11/17/2022,2022-11-17,3,-1664.812664,0.056663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6226,Last Knights,65.0,"Action, Adventure","When an evil emperor executes their leader, hi...","Clive Owen, Raiden, Morgan Freeman, Bartok, Ak...",Last Knights,Released,English,40000000.0,3643591.0,AU,05/27/2015,2015-05-27,4,-997.818059,0.091090
6230,My Student's Mom 2,10.0,Romance,"Jong-min, a tutor, keeps attracting attention ...","Kim In-ae, , Choi Woo-suk-I, , Park Hyun-jung,...",내 학생의 엄마 2,Released,Korean,201940000.0,38157314.0,KR,11/09/2017,2017-11-09,1,-429.230123,0.188954
6234,Perfect Sense,69.0,"Drama, Science Fiction, Romance","In Glasgow, Scotland, while a mysterious pande...","Ewan McGregor, Michael, Eva Green, Susan, Ewen...",Perfect Sense,Released,English,12200120.0,138868.0,GB,10/07/2011,2011-10-07,4,-8685.407725,0.011383
6238,Metallica: Through the Never,68.0,Music,"Trip, a young roadie for Metallica, is sent on...","Dane DeHaan, Trip, James Hetfield, Himself, La...",Metallica: Through the Never,Released,English,18000000.0,7972967.0,AU,12/02/2013,2013-12-02,4,-125.762881,0.442943
6241,Marshall,73.0,Drama,"Thurgood Marshall, the first African-American ...","Chadwick Boseman, Thurgood Marshall, Josh Gad,...",Marshall,Released,English,12000000.0,10116816.0,AU,06/07/2020,2020-06-07,4,-18.614394,0.843068

In [178]:
df.to_csv('../data/golden/imdb_movies_tratado.csv', index=False)